### ISSUE TITLE
 #warning Use Unknown board and EEPROM

### ISSUE THREAD

**Issue by AdaBill** [khoih-prog/Timezone_Generic#1]
I'm using Arduino 1.8.13 with latest ESP32 add on package and tried to use this with your tzTest. tried on an ESP32 WROOM-32 and  a ESP8266 NODEMCU boards and had this issue! Here is the listing for the ESP8266.
[TimeZone_Generic_ERROR.txt](https://github.com/khoih-prog/Timezone_Generic/files/5526896/TimeZone_Generic_ERROR.txt)

**Comment by khoih-prog** [comment]
Hi @AdaBill 

Thanks for your interest in the [**Timezone_Generic Library**](https://github.com/khoih-prog/Timezone_Generic) .

I'm sorry this [**Timezone_Generic Library**](https://github.com/khoih-prog/Timezone_Generic) is currently not supporting ESP32/ESP8266. I'm planning to add the support within days.

You can have a look at [Supported Bboards](https://github.com/khoih-prog/Timezone_Generic#supported-boards)

> ### Supported Boards
> - ESP8266. To be done soon.
> - ESP32. . To be done soon.

If it's urgent, I suggest that you can try to use the original [**Timezone Library**](https://github.com/JChristensen/Timezone)

Good Luck,
