### ISSUE TITLE
Linker error

### ISSUE THREAD

**Issue by bmcdonnell** [khoih-prog/Timezone_Generic#4]
Thanks for your work on this.

What is the purpose of the header only implementation of this library? Since it can produce the [known linker error issue](https://github.com/khoih-prog/Timezone_Generic#howto-fix-multiple-definitions-linker-error), and its contents are nearly identical to the `src_cpp` version, I think this library would be improved by having only the `src_cpp` version.

### Describe the bug

Linker error

```
multiple definition of `Timezone::display_STD_Rule()
```

### Steps to Reproduce

Build.

### Expected behavior

Clean build.

### Actual behavior

Linker error.

### Debug and AT-command log (if applicable)

N/A.

### Screenshots

N/A.

### Information

```
Arduino IDE version: 1.8.13
OS: Windows 10 version 1909 (OS Build 18363.1440)
Board: Adafruit Metro M4 AirLift
Board lib: Adafruit SAMD Boards library v1.6.7
```

> * `ESP8266`,`ESP32` or `STM32` Core Version (e.g. ESP8266 core v2.7.4, ESP32 v1.0.5 or STM32 v1.9.0)

I'm not sure if this applies. Where would I find it?
```

### Additional context

N/A

**Comment by bmcdonnell** [comment]
> But you need to do some research why header-only implementation is better.

The "pros" such as discussed on [this SO post](https://softwareengineering.stackexchange.com/a/305620/177673) seem like premature optimization to me. Unless you've profiled and found the need?

> I don't like to make life easy without real benefit.

IMO, preventing a linker error for your users would be a real benefit. It takes time for us to find the source for the error, then your explanation, then to work around it as you've described. It complicates upgrading for us, too, since we have to modify the library each time. (Within the Arduino IDE, at least.)

Having to modify the library is unconventional and unexpected, especially since it's listed in the Arduino Library Manager.

What is the "real benefit" of having the header-only implementation in this instance?

**Comment by bmcdonnell** [comment]
@khoih-prog how do you prevent this linker error from the header-only version when using this library in your own applications?

**Comment by khoih-prog** [comment]
You can have a look at a simple solution at  [**multiple definition of `websockets2_generic::WebsocketsServer::~WebsocketsServer()'** in websocket2_generic library #3](https://github.com/khoih-prog/WebSockets2_Generic/issues/3)

Other simpler ways to do are

- to rename your cpp files to hpp files.
- convert aaa.cpp files to aaa-Impl.h files

I suggest you spend time to test all the options yourself, then find out **why the h-only is better** or worse, in which way.

Research by Googling is good, but don't trust everything you read, especially something 10-15 years old. It's always better you verify what you read before using.

I'm sorry I won't answer this topic anymore.
