### ISSUE TITLE
Invalid license?

### ISSUE THREAD

**Issue by bmcdonnell** [khoih-prog/Timezone_Generic#5]
# Background

Per this library's README:

> This Timezone_Generic library is based on and modified from [Jack Christensen's Timezone Library](https://github.com/JChristensen/Timezone)

# Problem

Jack Christensen's Timezone Library is released under the GNU GPL v3.0, but this Timezone_Generic library says it is released under the more permissive MIT license. As I understand it, this is not allowed for a derivative work, unless you've gotten permission from the copyright holder(s) of the original work.

# Solutions

I believe the easiest compliant solution would be to release Timezone_Generic under GPL v3.0. Alternatively, I think you'd need to get permission from the original work's copyright holder(s) to release it under a more permissive license (MIT, or whatever else you all agree to).

**Comment by khoih-prog** [comment]
Hi @bmcdonnell 

I got similar issue with other library, as I really didn't spend precious time to look at the Licence, as in previous issue with another  library : [**Clarification on the license?** #8](https://github.com/khoih-prog/AsyncHTTPRequest_Generic/issues/8)

> I'm sorry I didn't spent time to look at the licenses and see the differences. It doesn't matter to me if it's GPLv3 or MIT, as long as users can use the library easily.
> 
> If there is issue, I'll convert back to GPLv3 without any problem at all.
> 
> Thanks for pointing out.

I certainly change the Licence shortly. I'd appreciate it if you can spot anywhere else.

Regards,

**Comment by khoih-prog** [comment]
Done.
