### ISSUE TITLE
Cannot compile anymore on VScode with Platform IO on STM32 framework arduino

### ISSUE THREAD

**Issue by gcharles81** [khoih-prog/Timezone_Generic#6]
I have an application using this library with STM32 , but recently after VSCode update this library is not compiling anymore 

Somehow it something wrong with ArduinoSTL , 

//******************************************************************************************************************************************

.pio\libdeps\black_f407ve\ArduinoSTL\src/cmath:100:10: error: 'expf' was not declared in this scope; did you mean 'exp'?
  100 |   return expf(x);
      |          ^~~~
      |          exp
.pio\libdeps\black_f407ve\ArduinoSTL\src/cmath: In function 'float std::abs(float)':
.pio\libdeps\black_f407ve\ArduinoSTL\src/cmath:76:10: error: 'fabsf' was not declared in this scope; did you mean 'abs'?
   76 |   return fabsf(x);
      |          ^~~~~
      |          abs
.pio\libdeps\black_f407ve\ArduinoSTL\src/cmath: In function 'float std::acos(float)':
.pio\libdeps\black_f407ve\ArduinoSTL\src/cmath:79:10: error: 'acosf' was not declared in this scope; did you mean 'acos'?
   79 |   return acosf(x);
      |          ^~~~~
      |          acos
.pio\libdeps\black_f407ve\ArduinoSTL\src/cmath: In function 'float std::atan(float)':
.pio\libdeps\black_f407ve\ArduinoSTL\src/cmath:85:10: error: 'atanf' was not declared in this scope; did you mean 'atan'?
   85 |   return atanf(x);
      |          ^~~~~
      |          atan
.pio\libdeps\black_f407ve\ArduinoSTL\src/cmath: In function 'float std::fabs(float)':
.pio\libdeps\black_f407ve\ArduinoSTL\src/cmath:103:10: error: 'fabsf' was not declared in this scope; did you mean 'fabs'?
  103 |   return fabsf(x);
      |          ^~~~~
      |          fabs
.pio\libdeps\black_f407ve\ArduinoSTL\src/cmath: In function 'float std::acos(float)':
.pio\libdeps\black_f407ve\ArduinoSTL\src/cmath:79:10: error: 'acosf' was not declared in this scope; did you mean 'acos'?
   79 |   return acosf(x);
      |          ^~~~~
      |          acos
.pio\libdeps\black_f407ve\ArduinoSTL\src/cmath: In function 'float std::atan2(float, float)':
.pio\libdeps\black_f407ve\ArduinoSTL\src/cmath:88:10: error: 'atan2f' was not declared in this scope; did you mean 'atan2'?
   88 |   return atan2f(y, x);
      |          ^~~~~~
      |          atan2
.pio\libdeps\black_f407ve\ArduinoSTL\src/cmath: In function 'float std::asin(float)':
.pio\libdeps\black_f407ve\ArduinoSTL\src/cmath:82:10: error: 'asinf' was not declared in this scope; did you mean 'asin'?
   82 |   return asinf(x);
      |          ^~~~~
      |          asin
.pio\libdeps\black_f407ve\ArduinoSTL\src/cmath: In function 'float std::floor(float)':
.pio\libdeps\black_f407ve\ArduinoSTL\src/cmath:106:10: error: 'floorf' was not declared in this scope; did you mean 'floor'?
  106 |   return floorf(x);
      |          ^~~~~~
      |          floor
.pio\libdeps\black_f407ve\ArduinoSTL\src/cmath: In function 'float std::ceil(float)':
.pio\libdeps\black_f407ve\ArduinoSTL\src/cmath:91:10: error: 'ceilf' was not declared in this scope; did you mean 'ceil'?
   91 |   return ceilf(x);
      |          ^~~~~
      |          ceil
.pio\libdeps\black_f407ve\ArduinoSTL\src/cmath: In function 'float std::atan(float)':
.pio\libdeps\black_f407ve\ArduinoSTL\src/cmath:85:10: error: 'atanf' was not declared in this scope; did you mean 'atan'?
   85 |   return atanf(x);
      |          ^~~~~
      |          atan
.pio\libdeps\black_f407ve\ArduinoSTL\src/cmath: In function 'float std::fmod(float, float)':
.pio\libdeps\black_f407ve\ArduinoSTL\src/cmath:109:10: error: 'fmodf' was not declared in this scope; did you mean 'fmod'?
  109 |   return fmodf(x, y);
      |          ^~~~~
      |          fmod
.pio\libdeps\black_f407ve\ArduinoSTL\src/cmath: In function 'float std::cos(float)':
.pio\libdeps\black_f407ve\ArduinoSTL\src/cmath:94:10: error: 'cosf' was not declared in this scope; did you mean 'cos'?
   94 |   return cosf(x);
      |          ^~~~
      |          cos
.pio\libdeps\black_f407ve\ArduinoSTL\src/cmath: In function 'float std::atan2(float, float)':
.pio\libdeps\black_f407ve\ArduinoSTL\src/cmath:88:10: error: 'atan2f' was not declared in this scope; did you mean 'atan2'?
   88 |   return atan2f(y, x);
      |          ^~~~~~
      |          atan2
.pio\libdeps\black_f407ve\ArduinoSTL\src/cmath: In function 'float std::frexp(float, int*)':
.pio\libdeps\black_f407ve\ArduinoSTL\src/cmath:112:10: error: 'frexpf' was not declared in this scope; did you mean 'frexp'?
  112 |   return frexpf(x, exp);
      |          ^~~~~~
      |          frexp
.pio\libdeps\black_f407ve\ArduinoSTL\src/cmath: In function 'float std::cosh(float)':
.pio\libdeps\black_f407ve\ArduinoSTL\src/cmath:97:10: error: 'coshf' was not declared in this scope; did you mean 'cosh'?
   97 |   return coshf(x);
      |          ^~~~~
      |          cosh
.pio\libdeps\black_f407ve\ArduinoSTL\src/cmath: In function 'float std::ceil(float)':
.pio\libdeps\black_f407ve\ArduinoSTL\src/cmath:91:10: error: 'ceilf' was not declared in this scope; did you mean 'ceil'?
   91 |   return ceilf(x);
      |          ^~~~~
      |          ceil
.pio\libdeps\black_f407ve\ArduinoSTL\src/cmath: In function 'float std::exp(float)':
.pio\libdeps\black_f407ve\ArduinoSTL\src/cmath:100:10: error: 'expf' was not declared in this scope; did you mean 'exp'?
  100 |   return expf(x);
      |          ^~~~
      |          exp
.pio\libdeps\black_f407ve\ArduinoSTL\src/cmath: In function 'float std::cos(float)':
.pio\libdeps\black_f407ve\ArduinoSTL\src/cmath:94:10: error: 'cosf' was not declared in this scope; did you mean 'cos'?
   94 |   return cosf(x);
      |          ^~~~
      |          cos
.pio\libdeps\black_f407ve\ArduinoSTL\src/cmath: In function 'float std::fabs(float)':
.pio\libdeps\black_f407ve\ArduinoSTL\src/cmath:103:10: error: 'fabsf' was not declared in this scope; did you mean 'fabs'?
  103 |   return fabsf(x);
      |          ^~~~~
      |          fabs
.pio\libdeps\black_f407ve\ArduinoSTL\src/cmath: In function 'float std::ldexp(float, int)':
.pio\libdeps\black_f407ve\ArduinoSTL\src/cmath:115:10: error: 'ldexpf' was not declared in this scope; did you mean 'ldexp'?
  115 |   return ldexpf(x, exp);
      |          ^~~~~~
      |          ldexp
.pio\libdeps\black_f407ve\ArduinoSTL\src/cmath: In function 'float std::floor(float)':
.pio\libdeps\black_f407ve\ArduinoSTL\src/cmath:106:10: error: 'floorf' was not declared in this scope; did you mean 'floor'?
  106 |   return floorf(x);
      |          ^~~~~~
      |          floor
.pio\libdeps\black_f407ve\ArduinoSTL\src/cmath: In function 'float std::asin(float)':
.pio\libdeps\black_f407ve\ArduinoSTL\src/cmath:82:10: error: 'asinf' was not declared in this scope; did you mean 'asin'?
   82 |   return asinf(x);
      |          ^~~~~
      |          asin
.pio\libdeps\black_f407ve\ArduinoSTL\src/cmath: In function 'float std::cosh(float)':
.pio\libdeps\black_f407ve\ArduinoSTL\src/cmath:97:10: error: 'coshf' was not declared in this scope; did you mean 'cosh'?
   97 |   return coshf(x);
      |          ^~~~~
      |          cosh
.pio\libdeps\black_f407ve\ArduinoSTL\src/cmath: In function 'float std::atan(float)':
.pio\libdeps\black_f407ve\ArduinoSTL\src/cmath:85:10: error: 'atanf' was not declared in this scope; did you mean 'atan'?
   85 |   return atanf(x);
      |          ^~~~~
      |          atan
.pio\libdeps\black_f407ve\ArduinoSTL\src/cmath: In function 'float std::fmod(float, float)':
.pio\libdeps\black_f407ve\ArduinoSTL\src/cmath:109:10: error: 'fmodf' was not declared in this scope; did you mean 'fmod'?
//******************************************************************************************************************************************

Thank You

**Comment by khoih-prog** [comment]
Hi @gcharles81 

I'm sorry I don't have the same settings to duplicate and help you. 

Please post your issue on PIO Forum for help.
